version: '3'

services:
  database:
    container_name: bloodboiler-sql-database
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    logging:
      driver: none

  backend:
    container_name: bloodboiler-sql-backend
    build: ../..
    image: bloodboiler
    ports:
      - '3000:3000'
    volumes:
      - .:/opt/node_app/app
    networks:
      - app-network
    depends_on:
      - database

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
