version: '3'

services:
  api:
    environment:
      - DB_HOST=database
    build:
      context: .
      target: test
    image: bloodboiler-sql:latest
    command: >
      sh -c "npx sequelize-cli db:migrate \
             && npm test"
