version: '3'

services:
  database:
    container_name: database
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    logging:
      driver: none

  api:
    container_name: bloodboiler-sql-api
    ports:
      - '3000:3000'
    volumes:
      - .:/node/app:delegated
      - /node/app/node_modules
    networks:
      - app-network
    depends_on:
      - database

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
