#!/bin/bash
echo "PORT=3000
CLIENT_URL=http://localhost:3000

JWT_SECRET=$JWT_SECRET

ACCESS_TOKEN_EXPIRES_IN=7d
REFRESH_TOKEN_EXPIRES_IN=24h
RESET_TOKEN_EXPIRES_IN=1h

DB_NAME=node-bloodboiler
DB_HOST=$DB_HOST
DB_USER=$DB_USER
DB_PASS=$DB_PASS
MAIL_FROM=no-reply <$MAIL_USER>
MAIL_HOST=$MAIL_HOST
MAIL_PORT=$MAIL_PORT
MAIL_USER=$MAIL_USER
MAIL_PASS=$MAIL_PASS" > .env